source 'https://rubygems.org/'
gemspec

# gem 'rubysl-open-uri', '~> 2.0'
gem 'open_uri_redirections', '~> 0.2.1'
gem 'sinatra'
gem 'json'
gem 'pg', '0.20'
gem 'sinatra-activerecord'
gem 'pry'
# group :development do
#   gem "capistrano", "~> 3.10", require: false
# end

group :development do
  gem 'hoe'
  gem 'hoe-gemspec'
  gem 'hoe-git'
end

group :travis do
  gem 'hoe-travis'
end

group :testing do
  gem 'minitest'
  gem 'mocha'
end
